DefaultContentLanguage = "en"
baseurl = "https://anthonymichael.work"
title = "Anthony Michael Carrella"
# Using theme as git submodule 
theme = "sweetb-hugo"
# Or when using theme as hugo module
# theme = "github.com/jlumbroso/sweetb-hugo"
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"

[Params]
since = 2023
#  homeTitle = "SweetB Hugo Theme" # Set a different text for the header on the home page
comments = true 
commit = false 
dateFormat = "January 2, 2006" 
delayDisqus = true 
favicon = "img/favicon.ico" 
logo = "img/avatar-icon.png" # Expecting square dimensions
mainSections = ["post", "posts"] 
navbarCenteredLogo = false 
navbarFloating = false 
readingTime = false 
rss = true 
showRelatedPosts = true 
socialShare = true 
subtitle = "Community Leadership with Soul" 
useHLJS = true 
wordCount = true 
#  hideAuthor = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"
#  disclaimerText = "The opinions expressed herein are my own personal opinions and do not represent my employer’s view in any way."

[Author]
# Set only your "username" for default hosts and full URLs otherwise (e.g., "https://MyGitLab.org/username")
# email = "youremail@domain.com" 
# facebook = "username" 
github = "https://github.com/amcarrella3"
# instagram = "username" 
linkedin = "anthony-m-carrella-81329b99"
# mastodon = "url" 
# medium = "username" 
name = "Anthony Michael Carrella"
# paypal = "username" 
# spotify = "username" 
# twitter = "username" 
website = "anthonymichael.work"
# youtube = "user/username" # or channel/channelname

[[menu.main]]
name = "Home"
url = ""
weight = 1

[[menu.main]]
name = "About"
url = "page/about/"
weight = 3

[[menu.main]]
identifier = "samples"
name = "Samples"
weight = 2

# [[menu.main]]
# name = "Big Image Sample"
# parent = "samples"
# url = "post/2017-03-07-bigimg-sample"
# weight = 1

# [[menu.main]]
# name = "Math Sample"
# parent = "samples"
# url = "post/2017-03-05-math-sample"
# weight = 2

# [[menu.main]]
# name = "Code Sample"
# parent = "samples"
# url = "post/2016-03-08-code-sample"
# weight = 3

[[menu.main]]
name = "Tags"
url = "tags"
weight = 3
